### ISSUE TITLE
downlod wont workie >:(

### ISSUE THREAD

**Issue by Sonickirbystar** [Cracko298/MC3DS-Multiplayer-Mod#1]
how to ge the download working how?

**Comment by Sonickirbystar** [comment]
this a joke btw.

**Comment by Cracko298** [comment]
> how to ge the download working how?

Lol, the update/client is taking its time to finish

**Comment by LeiaFox** [comment]
this may be rude, but when do you think any type of prototype will be published?

**Comment by Cracko298** [comment]
> this may be rude, but when do you think any type of prototype will be published?

No telling, but it won't be released until it's at least usable.
Currently, it's extremely buggy, and heavily relies on the Latency with your console and your computer itself communicating.
Right now, it's nearly 1500ms (1.5 seconds) which will cutout the signal a lot of the time.
Rendering the game unusable practically unless you have about ~10ms ping on your console itself.

**Comment by Sonickirbystar** [comment]
> > this may be rude, but when do you think any type of prototype will be published?
> 
> No telling, but it won't be released until it's at least usable. Currently, it's extremely buggy, and heavily relies on the Latency with your console and your computer itself communicating. Right now, it's nearly 1500ms (1.5 seconds) which will cutout the signal a lot of the time. Rendering the game unusable practically unless you have about ~10ms ping on your console itself.

Will it work with more then 2 people on a server? Or is having more then 2 going to cause issues.

**Comment by Cracko298** [comment]
> Will it work with more then 2 people on a server? Or is having more then 2 going to cause issues.

There is no code that is preventing connections, really its just a limit that's emposed, which can be bypassed easily externally. However, this can create a lot more Lag and latency between devices, so it's definitely possible, and has been tested with 2 others. However, it's extremely laggy, and disconnects are very frequent. 
I can't release an unfinished product, even if it is open source.

**Comment by Sonickirbystar** [comment]
> > Will it work with more then 2 people on a server? Or is having more then 2 going to cause issues.
> 
> There is no code that is preventing connections, really its just a limit that's emposed, which can be bypassed easily externally. However, this can create a lot more Lag and latency between devices, so it's definitely possible, and has been tested with 2 others. However, it's extremely laggy, and disconnects are very frequent. I can't release an unfinished product, even if it is open source.

Oh I was just asking if you the creator of this project if it would be possible for more then just 2 players. I remember talking on you in the Minecraft 3DS Community Discord and about all the mutiplayer stuff being handled on the PC's end helping with 3ds performance (If I recall correctly). So would it be possible to have opmtiziations to help handle the lag. I understand the project is one not ready for public release or release in general which I understand and can wait. Your the big tech nerd with this stuff and I have no idea 🤷‍♂️ .

**Comment by Cracko298** [comment]
> Oh I was just asking if you the creator of this project if it would be possible for more then just 2 players. I remember talking on you in the Minecraft 3DS Community Discord and about all the mutiplayer stuff being handled on the PC's end helping with 3ds performance (If I recall correctly). So would it be possible to have opmtiziations to help handle the lag. I understand the project is one not ready for public release or release in general which I understand and can wait. Your the big tech nerd with this stuff and I have no idea 🤷‍♂️ .

Ahh, see, it's 100% possible to have more than two people in a server.
The problem is that while yes, the PC (Client Part) is handling all the packets and everything, the 3ds is still rendering, calculating, and everything else that the data packets send over. It would relieve some strain on one part of the console but put more on another (cpu and gpu).

And yes, the PC Client itself could offer optimizations for the packets it doesn't really travel nicely into real-world performance.

**Comment by Sonickirbystar** [comment]
> > Oh I was just asking if you the creator of this project if it would be possible for more then just 2 players. I remember talking on you in the Minecraft 3DS Community Discord and about all the mutiplayer stuff being handled on the PC's end helping with 3ds performance (If I recall correctly). So would it be possible to have opmtiziations to help handle the lag. I understand the project is one not ready for public release or release in general which I understand and can wait. Your the big tech nerd with this stuff and I have no idea 🤷‍♂️ .
> 
> Ahh, see, it's 100% possible to have more than two people in a server. The problem is that while yes, the PC (Client Part) is handling all the packets and everything, the 3ds is still rendering, calculating, and everything else that the data packets send over. It would relieve some strain on one part of the console but put more on another (cpu and gpu).
> 
> And yes, the PC Client itself could offer optimizations for the packets it doesn't really travel nicely into real-world performance.

So how many players do you reccomand if I want to host a server for like small group. 3,4, or etc. players until the 3ds cant handle it no more or its just unplayable causing crashes.

**Comment by Cracko298** [comment]
> So how many players do you reccomand if I want to host a server for like small group. 3,4, or etc. players until the 3ds cant handle it no more or its just unplayable causing crashes.

I can't say for sure. I've only ever gotten 3 consoles hooked up, and it was rough.
2 of those consoles were mine, and on a 5ghz network with less than 15ms delay over wifi. The other console that was connected was @YT-Toaster's.

The recommended time at its current development is 2 players recommended as far as performance and stability are concerned.

And for the most players? I'd have to say maybe 4 or 5, but it's definitely not an enjoyable or really playable experience.

**Comment by Sonickirbystar** [comment]
> > So how many players do you reccomand if I want to host a server for like small group. 3,4, or etc. players until the 3ds cant handle it no more or its just unplayable causing crashes.
> 
> I can't say for sure. I've only ever gotten 3 consoles hooked up, and it was rough. 2 of those consoles were mine, and on a 5ghz network with less than 15ms delay over wifi. The other console that was connected was @YT-Toaster's.
> 
> The recommended time at its current development is 2 players recommended as far as performance and stability are concerned.
> 
> And for the most players? I'd have to say maybe 4 or 5, but it's definitely not an enjoyable or really playable experience.

So at aleast 3 people at best?

**Comment by Cracko298** [comment]
> So at aleast 3 people at best?

That's wishful thinking. Again, if it's not usable in the worst situations, then it really shouldn't be a thing to begin with.

The output on this project really just depends on if I can get the disconnects to stop.

2 people is really the goal. Other players are going to be an afterthought.

Please note to answer the release date question; it's not really a matter of "when" but rather a matter of "IF." If I cannot get it to work properly, then it probably won't be released or optimized for the public. Meaning to get it working will be a lot harder without the development environment it's currently in, or be scrapped all together.

**Comment by Cracko298** [comment]
> this may be rude, but when do you think any type of prototype will be published?

The answer provided in my most recent post sums it all up basically.

**Comment by ghost** [comment]
I'm here for the ride.
However I don't even have the source ;/

**Comment by Sonickirbystar** [comment]
baller (closing the issue)
